### PR TITLE
Allow compilation with MSVC 2008

### PR DESCRIPTION
**Pull request by ardovm**
The C compiler in Visual C++ 2008 lacks C99 support: all the variable declarations must be at the beginning of a block, and some headers are missing.
I needed to compile librsync with that compiler, for integration into a Python program.
I am opening this pull request in the hope that my work can be useful. If you reject it because you do not want to support C standards from the last century, I will not take it personal. ;-)

### CODE REVIEW

**Comment by ardovm** [comment]
I forgot to mention that these fixes only apply to the **library**. I am not sure it is even possible to make a Windows executable for rdiff?

**Comment by dbaarda** [comment]
I'm still thinking about this. 

I think we probably don't want to burden ourselves too much with supporting pre C99 compilers, and did a bunch of cleanups on the basis that life is much simpler if you assume C99.

However, if there really is demand for MSVC++ 2005, I guess it's not too bad.

I'm inclined to leave this PR here and see how much demand it gets before we decide if we want it or not.

**Comment by ardovm** [comment]
Hello,
for what it's worth: I got into this because I had to build a current release of rdiff-backup, that is written in Python version 2.7. This pulled MSVC++ 2005 in.
I appreciate you are taking into account this request, anyway.
I can get along with my own fork, of course. I just wanted to share my work in case it could be useful for anyone else.

**Comment by ericzolf** [comment]
The rdiff-backup project is alive again and ported to Python 3. Windows support has been broken and needs some love, my next task is indeed to get librsync compiled automatically on Windows, as a Linux guy...

**Comment by ardovm** [comment]
I apologize, I am messing up my branch and therefore this PR. git will never be my cup of tea.

I will close this PR because, as @ericzolf correctly reported, rdiff-backup is going to work on Python 3.

Feel free to contact me if you think this topic will come of interest again in the future.

**Pull request closed without merging**
