### PR TITLE
Handle copy cb returning more data than requested

### PR DESCRIPTION
**Pull request by paulharris**
Addresses #35

### CODE REVIEW

**Comment by sourcefrog** [comment]
We need to hook the test into `configure.ac` so it actually runs.

**Comment by sourcefrog** [comment]
It looks like I should also clarify in the docs that the length passed in is a maximum.

**Comment by sourcefrog** [comment]
I wonder if we should just use only the part we want, even if the caller returned too much.  It could be just a warning.

**Comment by sourcefrog** [comment]
I merged the equivalent of the fix in https://github.com/librsync/librsync/commit/088600fb8f51cdacbbd8143b5fffc17994e838bf but we should still merge the test.

**Comment by sourcefrog** [comment]
I have an updated version of this test in https://github.com/sourcefrog/librsync/tree/copy-cb2 but it's failing, despite the original bug apparently being fixed.

**Comment by dbaarda** [comment]
I just had a look at this in the interests of closing out this pull request.

IMHO a badly behaving callback is a programming error that violates the contract of the API. As such, we should not be adding defensive code that will be an overhead for good code in release builds. However, we should be adding asserts() that check the API contract is being honoured for debug builds.

I also spotted some inefficiency in that piece of code that should be fixed... So I might just fix that now.

**Comment by dbaarda** [comment]
Actually, I just looked at the current code (instead of just this patch), and I see the inefficiency has been fixed (unnecessary alloc/memcpy) and the code now just uses only the desired len if the callback returned more.

I still think asserts would have been better, but changing it now would arguably be a regression, so my motivation for doing anything with this has faded.

As I consider correctly handling a bad callback a bit of a non-feature, I don't really care about adding tests to check that it works... so IMHO this pull request should be dropped.

**Comment by paulharris** [comment]
ok

**Comment by dbaarda** [comment]
Looking a little closer I spotted another little bug which would make patch hang forever for an invalid delta file with a zero length copy instruction.

Also, the current code only emits a trace "warning message" when this happens, which means for builds with trace turned off it becomes invisible. Even with trace turned on it's likely to be missed in the trace noise. As this is likely an error developers should know about, I think it needs to be more visible than that.

So I've put together a patch that;

1. fixes the little buglet for bad patch files.
2. Uses assert() to check the copied length is valid so debug builds fail with an assert error.
3. Keeps the backwards-compatible defensive handling for non-debug builds but logs a warning.
4. Tidies up the trace output a little bit to only output the callback return value for errors.

At some stage in the future we might be able to remove 3. but I thought it wisest to leave it in for now. See #206 for details.

**Comment by dbaarda** [comment]
I'm pretty happy with #206 and don't think we need tests to exercise assert() API contract checking. 

I'm going to abandon this pull request.

**Pull request closed without merging**
